### ISSUE TITLE
Alex's Mobs 1.20.1 Crashes after flipping to the next page

### ISSUE THREAD

**Issue by resooox** [Alex-the-666/AlexsMobs#1718] opened 2023-07-15 20:07 UTC
Book opens correctly, but when you flip the page, the game crashes.

**Comment by AttacMage** [comment] 2023-07-15 23:53
Same issue happens here. On Forge, both versions 4.7.1.0 and 4.7.1.21.

**Comment by Jystro** [comment] 2023-07-16 12:06
This is a duplicate of #1717

**Closed as completed** 2023-12-15 20:48 UTC
