### ISSUE TITLE
summon the blue mosquito boss, the server is down

### ISSUE THREAD

**Issue by phamdinhben** [Alex-the-666/AlexsMobs#1660] opened 2023-06-21 08:38 UTC
This error is very serious.  i am playing version 1.20.  when you summon the blue mosquito boss, the server will be down and inaccessible

**Comment by HiGuysItsMeSussyBaka** [comment] 2023-06-21 17:13
this is just a duplicate of issue #1654

**Closed as completed** 2023-06-30 17:35 UTC
