### ISSUE TITLE
catfish eating pokemons from cobblemon and changing what pokemon they were

### ISSUE THREAD

**Issue by Legoego19** [Alex-the-666/AlexsMobs#2001] opened 2024-03-16 10:54 UTC
When a catfish eats a small pokemon and u punch it to get the pokemon back it turns to a totally different pokemon with placeholder stats and abilities.
Not sure If I should report it here or to the cobblemon team.

**Comment by Seamonster778778778788** [comment] 2024-06-09 14:05
duplicate of #2051

**Closed as completed** 2024-09-06 15:30 UTC
