### ISSUE TITLE
Leafcutter ant hills spawning by the thousands in my world.

### ISSUE THREAD

**Issue by Camawama** [Alex-the-666/AlexsMobs#963] opened 2022-02-21 17:15 UTC
I created a new world today to further test out my modpack and noticed a lot of Leafcutter ant hills. The game was lagging really bad to I typed the command "/kill @e[type=alexsmobs:leafcutterant]" and it killed thousands at once. This, in turn, caused my game to be less laggy. I flew around the world and noticed the hills were everywhere and spawning more and more ants. I logged out of the world and attempted to log back in which caused my to see a bunch of ant entities for a split second and then the screen went grey (My guess is the game ran out of memory).

Minecraft Version: 1.18.1
Forge Version: 39.0.79
Mod Version: 1.17.1

Mod List: https://pastebin.com/6rVhczFV
World Seed: -1925822649969840498
Log File: [latest.log](https://github.com/Alex-the-666/AlexsMobs/files/8111068/latest.log)
Screenshots: 
![image](https://user-images.githubusercontent.com/43620900/155000997-b5ebb932-e8b7-48af-b812-029543caebfc.png)
![image](https://user-images.githubusercontent.com/43620900/155001111-a3961f91-d3df-47af-81ed-9cf7c689b0c9.png)

**Comment by herman-hassel** [comment] 2022-03-26 19:30
I am having the same issue with mod 1.17.4 for MC 1.18.1 using forge 39.1.2.

**Comment by nonchip** [comment] 2022-05-02 05:36
by the way this sounds like a duplicate of #839

**Closed as completed** 2022-09-16 20:05 UTC
