### ISSUE TITLE
Weird issue with item stacking [IMPORTANT]

### ISSUE THREAD

**Issue by Gamershy** [Alex-the-666/AlexsMobs#1112] opened 2022-06-01 09:34 UTC
I have this mod included in a custom modpack I've made. The installation was partially required for another mod, Integrated Dungeons and Structures, to be precise. As soon as I had installed the mods, an issue cropped up where crafted items would be given a tag internally with absolutely NO data in it (confirmed by opening the world in Universal Minecraft Editor), but items picked up from mob drops or by breaking blocks do not have a tag. This empty tag causes the items to be unable to stack together, due to differing data, and causes annoying inventory clutter. Weirdly enough, dropping the items on the ground will allow the stacks to combine again, taking on the tag amongst the whole stack, depending on which stack was larger, which is incredibly odd.

This affects ALL items, modded or otherwise. I have confirmed this mod to be the culprit via systematically removing recently installed mods one after another. As soon as this mod was removed, the issue stopped, as soon as it was readded, it returned.

I honestly am confused as to how this issue could even be caused by this mod, unless it's a leftover from the Mimicreams or something. I have over 80 mods installed, and will actively check to see if there's somehow a conflict between mods causing this issue if requested, though it's unlikely as, again, this mod being removed instantly fixed the issue, and readding it caused it to happen again.

Do fix this asap, as this issue is EXTREMELY annoying, especially when working with large builds with a full inventory.

**Comment by Gbergz** [comment] 2022-06-02 00:11
Can confirm, this was an issue in earlier versions aswell, but got fixed. Seems it's back again.
Annoying issue for sure.
Edit: This for me wasn't caused by Alex's Mobs, thought so initially but forgot about this issue. It was Materialis. Now fixed in their mod.

**Closed as completed** 2022-06-12 16:57 UTC
