### ISSUE TITLE
Version 1.20 this bug is very serious. summon the blue mosquito  boss, the server is down

### ISSUE THREAD

**Issue by phamdinhben** [Alex-the-666/AlexsMobs#1661] opened 2023-06-21 09:12 UTC

**Comment by HiGuysItsMeSussyBaka** [comment] 2023-06-21 17:13
this is just a duplicate of issue #1654

**Comment by AlexModGuy** [comment] 2023-06-30 17:32
fixed

**Closed as completed by AlexModGuy** 2023-06-30 17:32 UTC
