### ISSUE TITLE
World Failed to Load

### ISSUE THREAD

**Issue by IRonicBruh** [Alex-the-666/AlexsMobs#177] opened 2021-02-09 04:41 UTC
Just trying to load my world after updating to the latest version of Alex's mobs + Citdael. 

Report: https://gist.github.com/IRonicBruh/357ba7e0dd79e48d7e5fbdfd1552cd5e

**Comment by NJL5390** [comment] 2021-02-09 12:11
I am also getting this issue. 
This happens every time I try to load a world:
![Screenshot 2021-02-09 12 04 53](https://user-images.githubusercontent.com/64381954/107361296-13ece980-6acf-11eb-8917-f8226c79654d.png)
Here's my latest log: https://pastebin.com/a2jk6buf

This only started happening when I updated Alex's mobs to 1.5.1 and I if I revert back to 1.5.0 it stops happening.
(Forge Version is 36.0.15).

I also can't seem to reproduce this with only Alex's Mobs installed so it seems like it could be a conflict with another mod.

Also this issue might be a duplicate of: https://github.com/Alex-the-666/AlexsMobs/issues/171

**Comment by ofelipescherer** [comment] 2021-02-09 13:40
I was having the same issue.

It's most likely an incompatibility with The Undergarden mod (https://www.curseforge.com/minecraft/mc-mods/the-undergarden)

**Comment by D-Bigboy-302** [comment] 2021-02-09 14:49
Hm.. It may be more than the undergarden. I'm having this issue as well but I don't have the undergarden installed. Can't pinpoint which mod is conflicting because I have over 100

**Comment by NJL5390** [comment] 2021-02-09 14:55
> It's most likely an incompatibility with The Undergarden mod (https://www.curseforge.com/minecraft/mc-mods/the-undergarden)

I don't have this mod installed and I'm still getting this issue. Although what is happening with that mod could give an indication as to what is causing the issue with other mods too. 

Either way, This issue definitely seems to be affecting multiple different mods.

**Comment by ST-Sebastian** [comment] 2021-02-09 15:04
I am also having this issue. It could be due to any world generation mods conflicting with this mod. Could be a simple render issue or a load issue that wasn't looked over by

**Comment by Lionhearte** [comment] 2021-02-09 19:08
Just wanted to report I'm also having this issue after latest update. I also have The Undergarden installed, but the previous version of AlexsMobs worked fine with it.

**Comment by luffykick** [comment] 2021-02-09 21:51
I can also confirm this error... My pack has just under 400 mods... with no Undergarden installed.

**Comment by ST-Sebastian** [comment] 2021-02-09 22:47
For now, until a later fix is available for this particular issue I would recommend using 1.4.1

**Comment by Alex-the-666** [comment] 2021-02-10 04:25
hmmm. try the latest citadel version with alexsmobs 1.5.1. https://www.curseforge.com/minecraft/mc-mods/citadel/files/3198842

**Comment by D-Bigboy-302** [comment] 2021-02-10 06:26
That seemed to fix it for me! No problems. Thanks!

**Comment by NJL5390** [comment] 2021-02-10 12:54
> hmmm. try the latest citadel version with alexsmobs 1.5.1. https://www.curseforge.com/minecraft/mc-mods/citadel/files/3198842

This appear to have worked for me as well! Thanks a lot!

**Comment by ST-Sebastian** [comment] 2021-02-10 15:06
Updating to the latest Citadel fixed the issue

**Comment by harmalom** [comment] 2021-02-10 23:15
same problem, and I don't have Undergarden installed.

**Closed** 2021-05-06 21:01 UTC
